### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [donadigo/elementary-ide#12]
We should make a settings dialog, similar to one in Scratch, that allows theme changing, editor theme changing, and other various SourceView settings (which are currently hard-coded).

**Comment by aleksandar-stefanovic** [comment]
I've successfully created a settings stub, which takes info from gsettings (dconf?) and makes them available as variables (really simple with Granite.Services.Settings). The only issue is that I don't know how to create a new schema within dconf using scripts, I've done it manually instead of using a script. Since it requires sudo, I guess it needs to be done at "sudo make install".

Getting preferences is done as easily as:

> Settings settings = new Settings ();
> if (settings.dark_mode) // for example
> ...

**Comment by donadigo** [comment]
Hello, thanks for investigating! You can sumbit the pull request and it doesn't need to have the CMake set up for the gsettings schema, I will take care of that myself if you want :)

**Comment by aleksandar-stefanovic** [comment]
Okay, let me work on it a little more, and I will push a separate branch then (so that you could see the changes), and then you can merge that branch into master once you've tried it...

What is the the path that we should use in the settings? "org.donadigo.elementary-ide" ?

Also, what settings do you suggest adding? I can think up the theme and editor settings (similar to the Scratch ones), like auto-indent, color-scheme, etc. Well, actually, I don't have to add them all right away, it will be very easy to add more settings later...

**Comment by donadigo** [comment]
We should use "com.github.donadigo.elementary-ide". Also, yeah, you don't need to add all required keys, they can be added later.

**Comment by aleksandar-stefanovic** [comment]
Okay, on it :)

**Comment by aleksandar-stefanovic** [comment]
See #13
