### ISSUE TITLE
unable to create new project

### ISSUE THREAD

**Issue by openStove** [donadigo/elementary-ide#17]
Hi I've just cloned and build the latest version on 16.04, program was installed successfully, but on clicking on new project, nothing is happening...
I tried to launch it from the terminal, and there are no error messages...

**Comment by donadigo** [comment]
Hi, you should note that this project is in a developement currently (slow, but I try to commit every once in a while). Creating a project is simply not implemented yet, the button you see on the welcome screen is a placeholder, not an actual button that does something. I agree though that the README should mention that it's not a fully implemented IDE as of yet.

The main focus right now is to have the ability to open projects and get from their structure as much data as possible to have little set up in the IDE itself to continue working on a project.
