### ISSUE TITLE
IDE does not open

### ISSUE THREAD

**Issue by robertsanseries** [donadigo/elementary-ide#20]
Log Terminal: 
robertsanseries@robert-notebook:~$ elementary-ide
[INFO 21:48:57.579349] Application.vala:153: elementary IDE version: 0.1
[INFO 21:48:57.579545] Application.vala:155: Kernel version: 4.8.0-56-generic
[ERROR 21:48:58.337595] [GLib-GIO] **Settings schema 'com.github.donadigo.elementary-ide' does not contain a key named 'show-mini-map'**
Trace/breakpoint trap (imagem do núcleo gravada)

**Comment by btd1337** [comment]
Same error.

_[INFO 02:23:36.908987] Application.vala:153: elementary IDE version: 0.1
[INFO 02:23:36.909045] Application.vala:155: Kernel version: 4.8.0-56-generic
[ERROR 02:23:37.181686] [GLib-GIO] Settings schema 'com.github.donadigo.elementary-ide' does not contain a key named 'show-mini-map'
[1]    21131 trace trap (core dumped)  elementary-ide_

**Comment by robertsanseries** [comment]
@btd1337 A temporary workaround is to get back some versions. I came back to `ee3eabaabc06cea73b88acab2cb2d0464763c82f` and it worked correctly.

Simply run on the terminal inside the main folder:
git reset --hard ee3eabaabc06cea73b88acab2cb2d0464763c82f

**Comment by donadigo** [comment]
Just merged a fix submitted by @jvictormmoreau that should solve the issue. Please pull again and see if it fixes the issue.

**Comment by robertsanseries** [comment]
@donadigo I confirm that problem has been resolved.

**Comment by donadigo** [comment]
Closing then.
