### ISSUE TITLE
Can't compile on latest Loki

### ISSUE THREAD

**Issue by rosavi** [donadigo/elementary-ide#24]
I wanted to mess around with it a bit (god knows vala sorely needs a good IDE), but couldn't even get it to compile.

This is the compiler output:

https://hastebin.com/qikokuxija.swift

**Comment by donadigo** [comment]
Sorry for not including the instructions how to compile, although I'm not really interested in developing this IDE, the focus has been lately on making Scratch, the default text editor in elementary OS, a full-fledged Vala IDE. You need to install `libvala-0.34-dev` package, if you are on Loki, you can simply do:
`sudo apt install libvala-0.34-dev`.

Keep in mind that this editor is nowhere near complete and can even cause data loss.
